package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BvlBillId generated by hbm2java
 */
@Embeddable
public class BvlBillId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String bbiInvoiceNumber;
     private String bbiBarcode;

    public BvlBillId() {
    }

    public BvlBillId(String bbiInvoiceNumber, String bbiBarcode) {
       this.bbiInvoiceNumber = bbiInvoiceNumber;
       this.bbiBarcode = bbiBarcode;
    }
   


    @Column(name="BBI_INVOICE_NUMBER", nullable=false, length=20)
    public String getBbiInvoiceNumber() {
        return this.bbiInvoiceNumber;
    }
    
    public void setBbiInvoiceNumber(String bbiInvoiceNumber) {
        this.bbiInvoiceNumber = bbiInvoiceNumber;
    }


    @Column(name="BBI_BARCODE", nullable=false, length=20)
    public String getBbiBarcode() {
        return this.bbiBarcode;
    }
    
    public void setBbiBarcode(String bbiBarcode) {
        this.bbiBarcode = bbiBarcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BvlBillId) ) return false;
		 BvlBillId castOther = ( BvlBillId ) other; 
         
		 return ( (this.getBbiInvoiceNumber()==castOther.getBbiInvoiceNumber()) || ( this.getBbiInvoiceNumber()!=null && castOther.getBbiInvoiceNumber()!=null && this.getBbiInvoiceNumber().equals(castOther.getBbiInvoiceNumber()) ) )
 && ( (this.getBbiBarcode()==castOther.getBbiBarcode()) || ( this.getBbiBarcode()!=null && castOther.getBbiBarcode()!=null && this.getBbiBarcode().equals(castOther.getBbiBarcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBbiInvoiceNumber() == null ? 0 : this.getBbiInvoiceNumber().hashCode() );
         result = 37 * result + ( getBbiBarcode() == null ? 0 : this.getBbiBarcode().hashCode() );
         return result;
   }   


}


