package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1

import java.util.Comparator;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BvlBill generated by hbm2java
 */
@Entity
@Table(name = "BVL_BILL", schema = "ebanktest")
public class BvlBill implements java.io.Serializable, Comparator<BvlBill> {
	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BvlBillId id;
	private String bbiId;
	private String bbiCompanyCode;
	private String bbiOutletNumber;
	private long bbiInvoiceAmount;
	private String bbiAccountNumber;
	private String bbiPolicyholder;
	private Date bbiFromDate;
	private Date bbiToDate;
	private String bbiDataSource;
	private String bbiInvoiceType;
	private String bbiChannelFreeRegister;
	private String bbiChannelFreePerform;
	private String bbiStatus;
	private Date bbiFeeDate;
	private Date bbiEffectiveDate;
	private String bbiTransactionCoCode;
	private String bbiTransactionId;
	private Date bbiLastUpdatedDate;
	private String bbiBankAccount;
	private String bbiCifNumber;
	private Date bbiRegisterFeeDate;
	private String bbiBankRegister;
	private String bbiBankPerform;
	private Date bbiInvoiceEdate;
	private String bbiPaymentInstruction;
	private String bbiPaymentOutlet;
	private String bbiTransactionInputter;
	private String bbiTransactionAuthoriser;
	private Long bbiTransactionAmount;
	private String bbiFileIn;
	private Date bbiTimeIn;
	private String bbiFileCoreOut;
	private String bbiFileOut;
	private Date bbiTimeOut;
	private Date bbiTimeCoreOut;

	public BvlBill() {
	}

	public BvlBill(BvlBillId id, String bbiId, String bbiCompanyCode, String bbiOutletNumber, long bbiInvoiceAmount) {
		this.id = id;
		this.bbiId = bbiId;
		this.bbiCompanyCode = bbiCompanyCode;
		this.bbiOutletNumber = bbiOutletNumber;
		this.bbiInvoiceAmount = bbiInvoiceAmount;
	}

	public BvlBill(BvlBillId id, String bbiId, String bbiCompanyCode, String bbiOutletNumber, long bbiInvoiceAmount,
			String bbiAccountNumber, String bbiPolicyholder, Date bbiFromDate, Date bbiToDate, String bbiDataSource,
			String bbiInvoiceType, String bbiChannelFreeRegister, String bbiChannelFreePerform, String bbiStatus,
			Date bbiFeeDate, Date bbiEffectiveDate, String bbiTransactionCoCode, String bbiTransactionId,
			Date bbiLastUpdatedDate, String bbiBankAccount, String bbiCifNumber, Date bbiRegisterFeeDate,
			String bbiBankRegister, String bbiBankPerform, Date bbiInvoiceEdate, String bbiPaymentInstruction,
			String bbiPaymentOutlet, String bbiTransactionInputter, String bbiTransactionAuthoriser,
			Long bbiTransactionAmount, String bbiFileIn, Date bbiTimeIn, String bbiFileCoreOut, String bbiFileOut,
			Date bbiTimeOut, Date bbiTimeCoreOut) {
		this.id = id;
		this.bbiId = bbiId;
		this.bbiCompanyCode = bbiCompanyCode;
		this.bbiOutletNumber = bbiOutletNumber;
		this.bbiInvoiceAmount = bbiInvoiceAmount;
		this.bbiAccountNumber = bbiAccountNumber;
		this.bbiPolicyholder = bbiPolicyholder;
		this.bbiFromDate = bbiFromDate;
		this.bbiToDate = bbiToDate;
		this.bbiDataSource = bbiDataSource;
		this.bbiInvoiceType = bbiInvoiceType;
		this.bbiChannelFreeRegister = bbiChannelFreeRegister;
		this.bbiChannelFreePerform = bbiChannelFreePerform;
		this.bbiStatus = bbiStatus;
		this.bbiFeeDate = bbiFeeDate;
		this.bbiEffectiveDate = bbiEffectiveDate;
		this.bbiTransactionCoCode = bbiTransactionCoCode;
		this.bbiTransactionId = bbiTransactionId;
		this.bbiLastUpdatedDate = bbiLastUpdatedDate;
		this.bbiBankAccount = bbiBankAccount;
		this.bbiCifNumber = bbiCifNumber;
		this.bbiRegisterFeeDate = bbiRegisterFeeDate;
		this.bbiBankRegister = bbiBankRegister;
		this.bbiBankPerform = bbiBankPerform;
		this.bbiInvoiceEdate = bbiInvoiceEdate;
		this.bbiPaymentInstruction = bbiPaymentInstruction;
		this.bbiPaymentOutlet = bbiPaymentOutlet;
		this.bbiTransactionInputter = bbiTransactionInputter;
		this.bbiTransactionAuthoriser = bbiTransactionAuthoriser;
		this.bbiTransactionAmount = bbiTransactionAmount;
		this.bbiFileIn = bbiFileIn;
		this.bbiTimeIn = bbiTimeIn;
		this.bbiFileCoreOut = bbiFileCoreOut;
		this.bbiFileOut = bbiFileOut;
		this.bbiTimeOut = bbiTimeOut;
		this.bbiTimeCoreOut = bbiTimeCoreOut;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bbiInvoiceNumber", column = @Column(name = "BBI_INVOICE_NUMBER", nullable = false, length = 20) ),
			@AttributeOverride(name = "bbiBarcode", column = @Column(name = "BBI_BARCODE", nullable = false, length = 20) ) })
	public BvlBillId getId() {
		return this.id;
	}

	public void setId(BvlBillId id) {
		this.id = id;
	}

	@Column(name = "BBI_ID", nullable = false, length = 9)
	public String getBbiId() {
		return this.bbiId;
	}

	public void setBbiId(String bbiId) {
		this.bbiId = bbiId;
	}

	@Column(name = "BBI_COMPANY_CODE", nullable = false, length = 9)
	public String getBbiCompanyCode() {
		return this.bbiCompanyCode;
	}

	public void setBbiCompanyCode(String bbiCompanyCode) {
		this.bbiCompanyCode = bbiCompanyCode;
	}

	@Column(name = "BBI_OUTLET_NUMBER", nullable = false, length = 10)
	public String getBbiOutletNumber() {
		return this.bbiOutletNumber;
	}

	public void setBbiOutletNumber(String bbiOutletNumber) {
		this.bbiOutletNumber = bbiOutletNumber;
	}

	@Column(name = "BBI_INVOICE_AMOUNT", nullable = false, precision = 12, scale = 0)
	public long getBbiInvoiceAmount() {
		return this.bbiInvoiceAmount;
	}

	public void setBbiInvoiceAmount(long bbiInvoiceAmount) {
		this.bbiInvoiceAmount = bbiInvoiceAmount;
	}

	@Column(name = "BBI_ACCOUNT_NUMBER", length = 14)
	public String getBbiAccountNumber() {
		return this.bbiAccountNumber;
	}

	public void setBbiAccountNumber(String bbiAccountNumber) {
		this.bbiAccountNumber = bbiAccountNumber;
	}

	@Column(name = "BBI_POLICYHOLDER", length = 100)
	public String getBbiPolicyholder() {
		return this.bbiPolicyholder;
	}

	public void setBbiPolicyholder(String bbiPolicyholder) {
		this.bbiPolicyholder = bbiPolicyholder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_FROM_DATE", length = 7)
	public Date getBbiFromDate() {
		return this.bbiFromDate;
	}

	public void setBbiFromDate(Date bbiFromDate) {
		this.bbiFromDate = bbiFromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_TO_DATE", length = 7)
	public Date getBbiToDate() {
		return this.bbiToDate;
	}

	public void setBbiToDate(Date bbiToDate) {
		this.bbiToDate = bbiToDate;
	}

	@Column(name = "BBI_DATA_SOURCE", length = 2)
	public String getBbiDataSource() {
		return this.bbiDataSource;
	}

	public void setBbiDataSource(String bbiDataSource) {
		this.bbiDataSource = bbiDataSource;
	}

	@Column(name = "BBI_INVOICE_TYPE", length = 2)
	public String getBbiInvoiceType() {
		return this.bbiInvoiceType;
	}

	public void setBbiInvoiceType(String bbiInvoiceType) {
		this.bbiInvoiceType = bbiInvoiceType;
	}

	@Column(name = "BBI_CHANNEL_FREE_REGISTER", length = 2)
	public String getBbiChannelFreeRegister() {
		return this.bbiChannelFreeRegister;
	}

	public void setBbiChannelFreeRegister(String bbiChannelFreeRegister) {
		this.bbiChannelFreeRegister = bbiChannelFreeRegister;
	}

	@Column(name = "BBI_CHANNEL_FREE_PERFORM", length = 2)
	public String getBbiChannelFreePerform() {
		return this.bbiChannelFreePerform;
	}

	public void setBbiChannelFreePerform(String bbiChannelFreePerform) {
		this.bbiChannelFreePerform = bbiChannelFreePerform;
	}

	@Column(name = "BBI_STATUS", length = 2)
	public String getBbiStatus() {
		return this.bbiStatus;
	}

	public void setBbiStatus(String bbiStatus) {
		this.bbiStatus = bbiStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_FEE_DATE", length = 7)
	public Date getBbiFeeDate() {
		return this.bbiFeeDate;
	}

	public void setBbiFeeDate(Date bbiFeeDate) {
		this.bbiFeeDate = bbiFeeDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_EFFECTIVE_DATE", length = 7)
	public Date getBbiEffectiveDate() {
		return this.bbiEffectiveDate;
	}

	public void setBbiEffectiveDate(Date bbiEffectiveDate) {
		this.bbiEffectiveDate = bbiEffectiveDate;
	}

	@Column(name = "BBI_TRANSACTION_CO_CODE", length = 20)
	public String getBbiTransactionCoCode() {
		return this.bbiTransactionCoCode;
	}

	public void setBbiTransactionCoCode(String bbiTransactionCoCode) {
		this.bbiTransactionCoCode = bbiTransactionCoCode;
	}

	@Column(name = "BBI_TRANSACTION_ID", length = 20)
	public String getBbiTransactionId() {
		return this.bbiTransactionId;
	}

	public void setBbiTransactionId(String bbiTransactionId) {
		this.bbiTransactionId = bbiTransactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_LAST_UPDATED_DATE", length = 7)
	public Date getBbiLastUpdatedDate() {
		return this.bbiLastUpdatedDate;
	}

	public void setBbiLastUpdatedDate(Date bbiLastUpdatedDate) {
		this.bbiLastUpdatedDate = bbiLastUpdatedDate;
	}

	@Column(name = "BBI_BANK_ACCOUNT", length = 30)
	public String getBbiBankAccount() {
		return this.bbiBankAccount;
	}

	public void setBbiBankAccount(String bbiBankAccount) {
		this.bbiBankAccount = bbiBankAccount;
	}

	@Column(name = "BBI_CIF_NUMBER", length = 30)
	public String getBbiCifNumber() {
		return this.bbiCifNumber;
	}

	public void setBbiCifNumber(String bbiCifNumber) {
		this.bbiCifNumber = bbiCifNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_REGISTER_FEE_DATE", length = 7)
	public Date getBbiRegisterFeeDate() {
		return this.bbiRegisterFeeDate;
	}

	public void setBbiRegisterFeeDate(Date bbiRegisterFeeDate) {
		this.bbiRegisterFeeDate = bbiRegisterFeeDate;
	}

	@Column(name = "BBI_BANK_REGISTER", length = 10)
	public String getBbiBankRegister() {
		return this.bbiBankRegister;
	}

	public void setBbiBankRegister(String bbiBankRegister) {
		this.bbiBankRegister = bbiBankRegister;
	}

	@Column(name = "BBI_BANK_PERFORM", length = 10)
	public String getBbiBankPerform() {
		return this.bbiBankPerform;
	}

	public void setBbiBankPerform(String bbiBankPerform) {
		this.bbiBankPerform = bbiBankPerform;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_INVOICE_EDATE", length = 7)
	public Date getBbiInvoiceEdate() {
		return this.bbiInvoiceEdate;
	}

	public void setBbiInvoiceEdate(Date bbiInvoiceEdate) {
		this.bbiInvoiceEdate = bbiInvoiceEdate;
	}

	@Column(name = "BBI_PAYMENT_INSTRUCTION", length = 2)
	public String getBbiPaymentInstruction() {
		return this.bbiPaymentInstruction;
	}

	public void setBbiPaymentInstruction(String bbiPaymentInstruction) {
		this.bbiPaymentInstruction = bbiPaymentInstruction;
	}

	@Column(name = "BBI_PAYMENT_OUTLET", length = 10)
	public String getBbiPaymentOutlet() {
		return this.bbiPaymentOutlet;
	}

	public void setBbiPaymentOutlet(String bbiPaymentOutlet) {
		this.bbiPaymentOutlet = bbiPaymentOutlet;
	}

	@Column(name = "BBI_TRANSACTION_INPUTTER", length = 50)
	public String getBbiTransactionInputter() {
		return this.bbiTransactionInputter;
	}

	public void setBbiTransactionInputter(String bbiTransactionInputter) {
		this.bbiTransactionInputter = bbiTransactionInputter;
	}

	@Column(name = "BBI_TRANSACTION_AUTHORISER", length = 50)
	public String getBbiTransactionAuthoriser() {
		return this.bbiTransactionAuthoriser;
	}

	public void setBbiTransactionAuthoriser(String bbiTransactionAuthoriser) {
		this.bbiTransactionAuthoriser = bbiTransactionAuthoriser;
	}

	@Column(name = "BBI_TRANSACTION_AMOUNT", precision = 12, scale = 0)
	public Long getBbiTransactionAmount() {
		return this.bbiTransactionAmount;
	}

	public void setBbiTransactionAmount(Long bbiTransactionAmount) {
		this.bbiTransactionAmount = bbiTransactionAmount;
	}

	@Column(name = "BBI_FILE_IN", length = 50)
	public String getBbiFileIn() {
		return this.bbiFileIn;
	}

	public void setBbiFileIn(String bbiFileIn) {
		this.bbiFileIn = bbiFileIn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_TIME_IN", length = 7)
	public Date getBbiTimeIn() {
		return this.bbiTimeIn;
	}

	public void setBbiTimeIn(Date bbiTimeIn) {
		this.bbiTimeIn = bbiTimeIn;
	}

	@Column(name = "BBI_FILE_CORE_OUT", length = 50)
	public String getBbiFileCoreOut() {
		return this.bbiFileCoreOut;
	}

	public void setBbiFileCoreOut(String bbiFileCoreOut) {
		this.bbiFileCoreOut = bbiFileCoreOut;
	}

	@Column(name = "BBI_FILE_OUT", length = 50)
	public String getBbiFileOut() {
		return this.bbiFileOut;
	}

	public void setBbiFileOut(String bbiFileOut) {
		this.bbiFileOut = bbiFileOut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_TIME_OUT", length = 7)
	public Date getBbiTimeOut() {
		return this.bbiTimeOut;
	}

	public void setBbiTimeOut(Date bbiTimeOut) {
		this.bbiTimeOut = bbiTimeOut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BBI_TIME_CORE_OUT", length = 7)
	public Date getBbiTimeCoreOut() {
		return this.bbiTimeCoreOut;
	}

	public void setBbiTimeCoreOut(Date bbiTimeCoreOut) {
		this.bbiTimeCoreOut = bbiTimeCoreOut;
	}

	@Override
	public int compare(BvlBill bill1, BvlBill bill2) {
		if (bill1.getBbiTransactionId() != null || bill2.getBbiTransactionId() != null)
			return bill1.getBbiTransactionId().compareTo(bill2.getBbiTransactionId());
		else
			return 0;
	}

}
