package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BvlCompanyId generated by hbm2java
 */
@Embeddable
public class BvlCompanyId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal bcoId;
     private String bcoCompanyCode;

    public BvlCompanyId() {
    }

    public BvlCompanyId(BigDecimal bcoId, String bcoCompanyCode) {
       this.bcoId = bcoId;
       this.bcoCompanyCode = bcoCompanyCode;
    }
   


    @Column(name="BCO_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getBcoId() {
        return this.bcoId;
    }
    
    public void setBcoId(BigDecimal bcoId) {
        this.bcoId = bcoId;
    }


    @Column(name="BCO_COMPANY_CODE", nullable=false, length=9)
    public String getBcoCompanyCode() {
        return this.bcoCompanyCode;
    }
    
    public void setBcoCompanyCode(String bcoCompanyCode) {
        this.bcoCompanyCode = bcoCompanyCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BvlCompanyId) ) return false;
		 BvlCompanyId castOther = ( BvlCompanyId ) other; 
         
		 return ( (this.getBcoId()==castOther.getBcoId()) || ( this.getBcoId()!=null && castOther.getBcoId()!=null && this.getBcoId().equals(castOther.getBcoId()) ) )
 && ( (this.getBcoCompanyCode()==castOther.getBcoCompanyCode()) || ( this.getBcoCompanyCode()!=null && castOther.getBcoCompanyCode()!=null && this.getBcoCompanyCode().equals(castOther.getBcoCompanyCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBcoId() == null ? 0 : this.getBcoId().hashCode() );
         result = 37 * result + ( getBcoCompanyCode() == null ? 0 : this.getBcoCompanyCode().hashCode() );
         return result;
   }   


}


