package vn.com.daisy.DAO;
// Generated Sep 24, 2016 4:44:10 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BvlCollateInfoId generated by hbm2java
 */
@Embeddable
public class BvlCollateInfoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte bciCollateType;
	private Date bciDate;

	public BvlCollateInfoId() {
	}

	public BvlCollateInfoId(byte bciCollateType, Date bciDate) {
		this.bciCollateType = bciCollateType;
		this.bciDate = bciDate;
	}

	@Column(name = "BCI_COLLATE_TYPE", nullable = false, precision = 2, scale = 0)
	public byte getBciCollateType() {
		return this.bciCollateType;
	}

	public void setBciCollateType(byte bciCollateType) {
		this.bciCollateType = bciCollateType;
	}

	@Column(name = "BCI_DATE", nullable = false, length = 7)
	public Date getBciDate() {
		return this.bciDate;
	}

	public void setBciDate(Date bciDate) {
		this.bciDate = bciDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BvlCollateInfoId))
			return false;
		BvlCollateInfoId castOther = (BvlCollateInfoId) other;

		return (this.getBciCollateType() == castOther.getBciCollateType())
				&& ((this.getBciDate() == castOther.getBciDate()) || (this.getBciDate() != null
						&& castOther.getBciDate() != null && this.getBciDate().equals(castOther.getBciDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBciCollateType();
		result = 37 * result + (getBciDate() == null ? 0 : this.getBciDate().hashCode());
		return result;
	}

}