package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BvlOutlet generated by hbm2java
 */
@Entity
@Table(name="BVL_OUTLET"
    ,schema="ebanktest"
)
public class BvlOutlet  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BvlOutletId id;
     private Long locationId;
     private String outletBvlifeId;
     private Long companyId;
     private String companyCode;
     private String companyBvlifeId;
     private String companyName;
     private Long salesOfficeId;
     private String salesOfficeCode;
     private String salesOfficeBvlifeId;
     private String salesOfficeName;
     private Long salesAgencyId;
     private String salesAgencyCode;
     private String salesAgencyBvlifeId;
     private String salesAgencyName;
     private Long salesUnitId;
     private String salesUnitCode;
     private String salesUnitBvlifeId;
     private String salesUnitName;
     private String outletName;
	private char status;

    public BvlOutlet() {
    }

	
    public BvlOutlet(BvlOutletId id) {
        this.id = id;
    }
    public BvlOutlet(BvlOutletId id, Long locationId, String outletBvlifeId, Long companyId, String companyCode, String companyBvlifeId, String companyName, Long salesOfficeId, String salesOfficeCode, String salesOfficeBvlifeId, String salesOfficeName, Long salesAgencyId, String salesAgencyCode, String salesAgencyBvlifeId, String salesAgencyName, Long salesUnitId, String salesUnitCode, String salesUnitBvlifeId, String salesUnitName, String outletName, char status) {
       this.id = id;
       this.locationId = locationId;
       this.outletBvlifeId = outletBvlifeId;
       this.companyId = companyId;
       this.companyCode = companyCode;
       this.companyBvlifeId = companyBvlifeId;
       this.companyName = companyName;
       this.salesOfficeId = salesOfficeId;
       this.salesOfficeCode = salesOfficeCode;
       this.salesOfficeBvlifeId = salesOfficeBvlifeId;
       this.salesOfficeName = salesOfficeName;
       this.salesAgencyId = salesAgencyId;
       this.salesAgencyCode = salesAgencyCode;
       this.salesAgencyBvlifeId = salesAgencyBvlifeId;
       this.salesAgencyName = salesAgencyName;
       this.salesUnitId = salesUnitId;
       this.salesUnitCode = salesUnitCode;
       this.salesUnitBvlifeId = salesUnitBvlifeId;
       this.salesUnitName = salesUnitName;
       this.outletName = outletName;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="outletId", column=@Column(name="OUTLET_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="outletNumber", column=@Column(name="OUTLET_NUMBER", nullable=false, length=100) ) } )
    public BvlOutletId getId() {
        return this.id;
    }
    
    public void setId(BvlOutletId id) {
        this.id = id;
    }

    
    @Column(name="LOCATION_ID", precision=10, scale=0)
    public Long getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="OUTLET_BVLIFE_ID", length=9)
    public String getOutletBvlifeId() {
        return this.outletBvlifeId;
    }
    
    public void setOutletBvlifeId(String outletBvlifeId) {
        this.outletBvlifeId = outletBvlifeId;
    }

    
    @Column(name="COMPANY_ID", precision=10, scale=0)
    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="COMPANY_CODE", length=10)
    public String getCompanyCode() {
        return this.companyCode;
    }
    
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    
    @Column(name="COMPANY_BVLIFE_ID", length=9)
    public String getCompanyBvlifeId() {
        return this.companyBvlifeId;
    }
    
    public void setCompanyBvlifeId(String companyBvlifeId) {
        this.companyBvlifeId = companyBvlifeId;
    }

    
    @Column(name="COMPANY_NAME", length=510)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="SALES_OFFICE_ID", precision=10, scale=0)
    public Long getSalesOfficeId() {
        return this.salesOfficeId;
    }
    
    public void setSalesOfficeId(Long salesOfficeId) {
        this.salesOfficeId = salesOfficeId;
    }

    
    @Column(name="SALES_OFFICE_CODE", length=10)
    public String getSalesOfficeCode() {
        return this.salesOfficeCode;
    }
    
    public void setSalesOfficeCode(String salesOfficeCode) {
        this.salesOfficeCode = salesOfficeCode;
    }

    
    @Column(name="SALES_OFFICE_BVLIFE_ID", length=9)
    public String getSalesOfficeBvlifeId() {
        return this.salesOfficeBvlifeId;
    }
    
    public void setSalesOfficeBvlifeId(String salesOfficeBvlifeId) {
        this.salesOfficeBvlifeId = salesOfficeBvlifeId;
    }

    
    @Column(name="SALES_OFFICE_NAME", length=510)
    public String getSalesOfficeName() {
        return this.salesOfficeName;
    }
    
    public void setSalesOfficeName(String salesOfficeName) {
        this.salesOfficeName = salesOfficeName;
    }

    
    @Column(name="SALES_AGENCY_ID", precision=10, scale=0)
    public Long getSalesAgencyId() {
        return this.salesAgencyId;
    }
    
    public void setSalesAgencyId(Long salesAgencyId) {
        this.salesAgencyId = salesAgencyId;
    }

    
    @Column(name="SALES_AGENCY_CODE", length=10)
    public String getSalesAgencyCode() {
        return this.salesAgencyCode;
    }
    
    public void setSalesAgencyCode(String salesAgencyCode) {
        this.salesAgencyCode = salesAgencyCode;
    }

    
    @Column(name="SALES_AGENCY_BVLIFE_ID", length=9)
    public String getSalesAgencyBvlifeId() {
        return this.salesAgencyBvlifeId;
    }
    
    public void setSalesAgencyBvlifeId(String salesAgencyBvlifeId) {
        this.salesAgencyBvlifeId = salesAgencyBvlifeId;
    }

    
    @Column(name="SALES_AGENCY_NAME", length=510)
    public String getSalesAgencyName() {
        return this.salesAgencyName;
    }
    
    public void setSalesAgencyName(String salesAgencyName) {
        this.salesAgencyName = salesAgencyName;
    }

    
    @Column(name="SALES_UNIT_ID", precision=10, scale=0)
    public Long getSalesUnitId() {
        return this.salesUnitId;
    }
    
    public void setSalesUnitId(Long salesUnitId) {
        this.salesUnitId = salesUnitId;
    }

    
    @Column(name="SALES_UNIT_CODE", length=10)
    public String getSalesUnitCode() {
        return this.salesUnitCode;
    }
    
    public void setSalesUnitCode(String salesUnitCode) {
        this.salesUnitCode = salesUnitCode;
    }

    
    @Column(name="SALES_UNIT_BVLIFE_ID", length=9)
    public String getSalesUnitBvlifeId() {
        return this.salesUnitBvlifeId;
    }
    
    public void setSalesUnitBvlifeId(String salesUnitBvlifeId) {
        this.salesUnitBvlifeId = salesUnitBvlifeId;
    }

    
    @Column(name="SALES_UNIT_NAME", length=510)
    public String getSalesUnitName() {
        return this.salesUnitName;
    }
    
    public void setSalesUnitName(String salesUnitName) {
        this.salesUnitName = salesUnitName;
    }

    
    @Column(name="OUTLET_NAME", length=510)
    public String getOutletName() {
        return this.outletName;
    }
    
    public void setOutletName(String outletName) {
        this.outletName = outletName;
    }

    
    @Column(name="STATUS", precision=2, scale=0)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


