package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BvlOutletId generated by hbm2java
 */
@Embeddable
public class BvlOutletId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long outletId;
     private String outletNumber;

    public BvlOutletId() {
    }

    public BvlOutletId(long outletId, String outletNumber) {
       this.outletId = outletId;
       this.outletNumber = outletNumber;
    }
   


    @Column(name="OUTLET_ID", nullable=false, precision=10, scale=0)
    public long getOutletId() {
        return this.outletId;
    }
    
    public void setOutletId(long outletId) {
        this.outletId = outletId;
    }


    @Column(name="OUTLET_NUMBER", nullable=false, length=100)
    public String getOutletNumber() {
        return this.outletNumber;
    }
    
    public void setOutletNumber(String outletNumber) {
        this.outletNumber = outletNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BvlOutletId) ) return false;
		 BvlOutletId castOther = ( BvlOutletId ) other; 
         
		 return (this.getOutletId()==castOther.getOutletId())
 && ( (this.getOutletNumber()==castOther.getOutletNumber()) || ( this.getOutletNumber()!=null && castOther.getOutletNumber()!=null && this.getOutletNumber().equals(castOther.getOutletNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOutletId();
         result = 37 * result + ( getOutletNumber() == null ? 0 : this.getOutletNumber().hashCode() );
         return result;
   }   


}


