package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SyslogsId generated by hbm2java
 */
@Embeddable
public class SyslogsId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal logId;
     private String logCode;

    public SyslogsId() {
    }

    public SyslogsId(BigDecimal logId, String logCode) {
       this.logId = logId;
       this.logCode = logCode;
    }
   


    @Column(name="LOG_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getLogId() {
        return this.logId;
    }
    
    public void setLogId(BigDecimal logId) {
        this.logId = logId;
    }


    @Column(name="LOG_CODE", nullable=false, length=12)
    public String getLogCode() {
        return this.logCode;
    }
    
    public void setLogCode(String logCode) {
        this.logCode = logCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SyslogsId) ) return false;
		 SyslogsId castOther = ( SyslogsId ) other; 
         
		 return ( (this.getLogId()==castOther.getLogId()) || ( this.getLogId()!=null && castOther.getLogId()!=null && this.getLogId().equals(castOther.getLogId()) ) )
 && ( (this.getLogCode()==castOther.getLogCode()) || ( this.getLogCode()!=null && castOther.getLogCode()!=null && this.getLogCode().equals(castOther.getLogCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLogId() == null ? 0 : this.getLogId().hashCode() );
         result = 37 * result + ( getLogCode() == null ? 0 : this.getLogCode().hashCode() );
         return result;
   }   


}


