package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Syslogs generated by hbm2java
 */
@Entity
@Table(name="SYSLOGS"
    ,schema="ebanktest"
    , uniqueConstraints = @UniqueConstraint(columnNames="LOG_ID") 
)
public class Syslogs  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SyslogsId id;
     private BigDecimal logclsId;
     private Date logDate;
     private BigDecimal userId;
     private BigDecimal wsId;
     private BigDecimal objId;
     private String objkeyCode;
     private BigDecimal eventId;
     private String eventCode;
     private String refNo;
     private Date refDate;
     private Boolean status;

    public Syslogs() {
    }

	
    public Syslogs(SyslogsId id) {
        this.id = id;
    }
    public Syslogs(SyslogsId id, BigDecimal logclsId, Date logDate, BigDecimal userId, BigDecimal wsId, BigDecimal objId, String objkeyCode, BigDecimal eventId, String eventCode, String refNo, Date refDate, Boolean status) {
       this.id = id;
       this.logclsId = logclsId;
       this.logDate = logDate;
       this.userId = userId;
       this.wsId = wsId;
       this.objId = objId;
       this.objkeyCode = objkeyCode;
       this.eventId = eventId;
       this.eventCode = eventCode;
       this.refNo = refNo;
       this.refDate = refDate;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="logId", column=@Column(name="LOG_ID", unique=true, nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="logCode", column=@Column(name="LOG_CODE", nullable=false, length=12) ) } )
    public SyslogsId getId() {
        return this.id;
    }
    
    public void setId(SyslogsId id) {
        this.id = id;
    }

    
    @Column(name="LOGCLS_ID", precision=22, scale=0)
    public BigDecimal getLogclsId() {
        return this.logclsId;
    }
    
    public void setLogclsId(BigDecimal logclsId) {
        this.logclsId = logclsId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOG_DATE", length=7)
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    
    @Column(name="USER_ID", precision=22, scale=0)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="WS_ID", precision=22, scale=0)
    public BigDecimal getWsId() {
        return this.wsId;
    }
    
    public void setWsId(BigDecimal wsId) {
        this.wsId = wsId;
    }

    
    @Column(name="OBJ_ID", precision=22, scale=0)
    public BigDecimal getObjId() {
        return this.objId;
    }
    
    public void setObjId(BigDecimal objId) {
        this.objId = objId;
    }

    
    @Column(name="OBJKEY_CODE", length=20)
    public String getObjkeyCode() {
        return this.objkeyCode;
    }
    
    public void setObjkeyCode(String objkeyCode) {
        this.objkeyCode = objkeyCode;
    }

    
    @Column(name="EVENT_ID", precision=22, scale=0)
    public BigDecimal getEventId() {
        return this.eventId;
    }
    
    public void setEventId(BigDecimal eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="EVENT_CODE", length=20)
    public String getEventCode() {
        return this.eventCode;
    }
    
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }

    
    @Column(name="REF_NO", length=20)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REF_DATE", length=7)
    public Date getRefDate() {
        return this.refDate;
    }
    
    public void setRefDate(Date refDate) {
        this.refDate = refDate;
    }

    
    @Column(name="STATUS", precision=1, scale=0)
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


