package vn.com.daisy.DAO;
// Generated Sep 27, 2016 9:44:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sysvar generated by hbm2java
 */
@Entity
@Table(name="SYSVAR"
    ,schema="ebanktest"
)
public class Sysvar  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String varName;
     private String dataType;
     private String varValue;
     private String varDesc;
     private Boolean mod;
     private String inputMask;

    public Sysvar() {
    }

	
    public Sysvar(String varName, String varValue) {
        this.varName = varName;
        this.varValue = varValue;
    }
    public Sysvar(String varName, String dataType, String varValue, String varDesc, Boolean mod, String inputMask) {
       this.varName = varName;
       this.dataType = dataType;
       this.varValue = varValue;
       this.varDesc = varDesc;
       this.mod = mod;
       this.inputMask = inputMask;
    }
   
     @Id 

    
    @Column(name="VAR_NAME", unique=true, nullable=false, length=20)
    public String getVarName() {
        return this.varName;
    }
    
    public void setVarName(String varName) {
        this.varName = varName;
    }

    
    @Column(name="DATA_TYPE", length=2)
    public String getDataType() {
        return this.dataType;
    }
    
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    
    @Column(name="VAR_VALUE", nullable=false, length=60)
    public String getVarValue() {
        return this.varValue;
    }
    
    public void setVarValue(String varValue) {
        this.varValue = varValue;
    }

    
    @Column(name="VAR_DESC", length=60)
    public String getVarDesc() {
        return this.varDesc;
    }
    
    public void setVarDesc(String varDesc) {
        this.varDesc = varDesc;
    }

    
    @Column(name="MOD", precision=1, scale=0)
    public Boolean getMod() {
        return this.mod;
    }
    
    public void setMod(Boolean mod) {
        this.mod = mod;
    }

    
    @Column(name="INPUT_MASK", length=12)
    public String getInputMask() {
        return this.inputMask;
    }
    
    public void setInputMask(String inputMask) {
        this.inputMask = inputMask;
    }




}


